theme: minima

title: Markus Lippert
author: Markus Lippert
description: Some projects, thoughts and other interesting stuff
permalink: pretty

twitter_username: lippert_markus
github_username:  lippertmarkus
facebook_username: lippertmarkus
linkedin_username: lippertmarkus
rss: RSS

show_excerpts: true
excerpt_separator: "\r\n"

google_analytics: UA-69344726-4
disqus:
    shortname: lippertmarkus

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

header_pages:
  - about.md
