theme: minima

title: Markus Lippert
author: Markus Lippert
description: Some projects, thoughts and other interesting stuff
permalink: pretty

twitter_username: lippert_markus
github_username:  lippertmarkus
facebook_username: lippertmarkus
linkedin_username: lippertmarkus
rss: RSS

show_excerpts: true

google_analytics: UA-NNNNNNNN-N

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

header_pages:
  - about.md
